AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Irish Rivers Data Scraper

  Serverless application that collects river data (flow, water level, temperature)
  from multiple sources including ESB Hydro PDFs and waterlevel.ie API,
  parses the data, and stores it in S3 for historical tracking and analysis.

# Global configuration for all resources
Globals:
  Function:
    Timeout: 120
    MemorySize: 256
    Runtime: python3.13
    Architectures:
      - arm64  # Graviton2 - 20% cheaper than x86
    Environment:
      Variables:
        ENVIRONMENT: production
        LOG_LEVEL: INFO

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  S3BucketName:
    Type: String
    Default: river-data-ireland
    Description: Name for the S3 bucket to store river data

  ScheduleExpression:
    Type: String
    Default: "rate(1 hour)"
    Description: EventBridge schedule expression (e.g., "rate(1 hour)" or "cron(0 * * * ? *)")

  WebAppBucketName:
    Type: String
    Default: river-guru-web
    Description: Name for the S3 bucket to host the River Guru web application

  Dash0OtlpEndpoint:
    Type: String
    Default: "https://ingress.europe-west4.gcp.dash0.com"
    Description: Dash0 OTLP/HTTP ingress endpoint

  Dash0AuthToken:
    Type: String
    NoEcho: true
    Default: ""
    Description: Dash0 authentication token (Bearer token)

Resources:
  # NOTE: S3 bucket for river data (river-data-ireland-prod) exists outside CloudFormation
  # Reference it directly using the S3BucketName parameter

  # IAM Role for Lambda function
  RiverDataCollectorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Basic Lambda execution (CloudWatch Logs)
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        # S3 permissions for the data bucket
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*
      Tags:
        - Key: Project
          Value: IrishRiversDataScraper
        - Key: Environment
          Value: !Ref Environment

  # ========================================
  # OpenTelemetry / Dash0 Observability
  # ========================================

  # Custom OTel Collector config packaged as a Lambda layer
  # The ADOT layer's bundled collector reads this from /opt/ to export to Dash0
  OtelCollectorConfigLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-otel-collector-config
      Description: Custom OpenTelemetry Collector configuration for Dash0
      Content: otel-collector-config/
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures:
        - arm64

  # Lambda function for collecting river data
  RiverDataCollectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-collector
      Description: Downloads and processes river data (flow, level, temperature) from multiple sources
      CodeUri: .
      Handler: src.lambda_handler.lambda_handler
      Role: !GetAtt RiverDataCollectorRole.Arn
      Layers:
        - arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-python-arm64-ver-1-32-0:2
        - !Ref OtelCollectorConfigLayer
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OPENTELEMETRY_COLLECTOR_CONFIG_URI: /opt/otel-collector-config.yaml
          OTEL_SERVICE_NAME: river-data-collector
          OTEL_PROPAGATORS: tracecontext,baggage
          DASH0_OTLP_ENDPOINT: !Ref Dash0OtlpEndpoint
          DASH0_AUTH_TOKEN: !Ref Dash0AuthToken
          S3_BUCKET_NAME: !Ref S3BucketName
          S3_REGION: !Ref AWS::Region
          S3_ENABLE_ENCRYPTION: "true"
          S3_STORAGE_CLASS: STANDARD
          # Data sources configuration (JSON array)
          DATA_SOURCES_JSON: |
            [
              {
                "station_id": "inniscarra",
                "name": "Inniscarra Dam",
                "river": "River Lee",
                "url": "http://www.esbhydro.ie/Lee/04-Inniscarra-Flow.pdf",
                "source_type": "pdf",
                "enabled": true
              },
              {
                "station_id": "lee_waterworks",
                "name": "Waterworks Weir",
                "river": "River Lee",
                "url": "https://waterlevel.ie/data/day/19102_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              },
              {
                "station_id": "blackwater_fermoy",
                "name": "Fermoy Town",
                "river": "River Blackwater",
                "url": "https://waterlevel.ie/data/day/18106_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              },
              {
                "station_id": "blackwater_mallow",
                "name": "Mallow Railway Bridge",
                "river": "River Blackwater",
                "url": "https://waterlevel.ie/data/day/18055_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              },
              {
                "station_id": "suir_golden",
                "name": "New Bridge (Golden)",
                "river": "River Suir",
                "url": "https://waterlevel.ie/data/day/16008_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              },
              {
                "station_id": "owenboy",
                "name": "Owenboy",
                "river": "River Owenboy",
                "url": "https://waterlevel.ie/data/day/19001_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              },
              {
                "station_id": "bandon_curranure",
                "name": "Curranure",
                "river": "River Bandon",
                "url": "https://waterlevel.ie/data/day/20002_{sensor}.csv",
                "source_type": "api",
                "enabled": true
              }
            ]
      Events:
        # EventBridge scheduled trigger
        HourlySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Trigger river data collection hourly
            Enabled: true
      Tags:
        Project: IrishRiversDataScraper
        Environment: !Ref Environment

  # CloudWatch Log Group with retention
  RiverDataCollectorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RiverDataCollectorFunction}
      RetentionInDays: 30

  # CloudWatch Alarm for Lambda errors
  RiverDataCollectorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-lambda-errors
      AlarmDescription: Alert when Lambda function encounters errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref RiverDataCollectorFunction
      TreatMissingData: notBreaching

  # CloudWatch Alarm for Lambda throttling
  RiverDataCollectorThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-lambda-throttles
      AlarmDescription: Alert when Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref RiverDataCollectorFunction
      TreatMissingData: notBreaching

  # ========================================
  # Phase 2: River Guru Web App Resources
  # ========================================

  # NOTE: S3 bucket for web app (river-guru-web-production) exists outside CloudFormation
  # Reference it directly using the WebAppBucketName parameter

  # IAM Role for Data API Lambda function
  DataApiLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-data-api-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*
      Tags:
        - Key: Project
          Value: RiverGuruWebApp
        - Key: Environment
          Value: !Ref Environment

  # Lambda function for Data API
  DataApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-data-api
      Description: REST API for accessing river flow data
      CodeUri: api/
      Handler: data_api.lambda_handler
      Role: !GetAtt DataApiLambdaRole.Arn
      Timeout: 30
      MemorySize: 256
      Layers:
        - arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-python-arm64-ver-1-32-0:2
        - !Ref OtelCollectorConfigLayer
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OPENTELEMETRY_COLLECTOR_CONFIG_URI: /opt/otel-collector-config.yaml
          OTEL_SERVICE_NAME: river-data-api
          OTEL_PROPAGATORS: tracecontext,baggage
          DASH0_OTLP_ENDPOINT: !Ref Dash0OtlpEndpoint
          DASH0_AUTH_TOKEN: !Ref Dash0AuthToken
          S3_BUCKET_NAME: !Ref S3BucketName
          S3_REGION: !Ref AWS::Region
          LOG_LEVEL: INFO
      Events:
        # API Gateway event for /latest endpoint
        GetLatestFlow:
          Type: Api
          Properties:
            Path: /api/flow/latest
            Method: GET
            RestApiId: !Ref RiverGuruApi
        # API Gateway event for /history endpoint
        GetHistoricalFlow:
          Type: Api
          Properties:
            Path: /api/flow/history
            Method: GET
            RestApiId: !Ref RiverGuruApi
        # OPTIONS for CORS preflight
        OptionsLatest:
          Type: Api
          Properties:
            Path: /api/flow/latest
            Method: OPTIONS
            RestApiId: !Ref RiverGuruApi
        OptionsHistory:
          Type: Api
          Properties:
            Path: /api/flow/history
            Method: OPTIONS
            RestApiId: !Ref RiverGuruApi
      Tags:
        Project: RiverGuruWebApp
        Environment: !Ref Environment

  # CloudWatch Log Group for Data API Lambda
  DataApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DataApiFunction}
      RetentionInDays: 30

  # API Gateway REST API
  RiverGuruApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Tags:
        Project: RiverGuruWebApp
        Environment: !Ref Environment

Outputs:
  # Lambda Function
  RiverDataCollectorFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt RiverDataCollectorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-function-arn

  RiverDataCollectorFunctionName:
    Description: Name of the Lambda function
    Value: !Ref RiverDataCollectorFunction
    Export:
      Name: !Sub ${AWS::StackName}-function-name

  # S3 Bucket (exists outside CloudFormation)
  RiverDataBucketName:
    Description: Name of the S3 bucket for river data
    Value: !Ref S3BucketName
    Export:
      Name: !Sub ${AWS::StackName}-bucket-name

  RiverDataBucketArn:
    Description: ARN of the S3 bucket
    Value: !Sub arn:aws:s3:::${S3BucketName}
    Export:
      Name: !Sub ${AWS::StackName}-bucket-arn

  # CloudWatch
  LogGroupName:
    Description: CloudWatch Log Group for Lambda function
    Value: !Ref RiverDataCollectorLogGroup

  # URLs
  S3ConsoleUrl:
    Description: URL to S3 bucket in AWS Console
    Value: !Sub https://s3.console.aws.amazon.com/s3/buckets/${S3BucketName}

  LambdaConsoleUrl:
    Description: URL to Lambda function in AWS Console
    Value: !Sub https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${RiverDataCollectorFunction}

  CloudWatchLogsUrl:
    Description: URL to CloudWatch Logs
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/${RiverDataCollectorLogGroup}

  # Phase 2: River Guru Web App Outputs
  RiverGuruApiUrl:
    Description: API Gateway endpoint URL for River Guru Data API
    Value: !Sub https://${RiverGuruApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-api-url

  RiverGuruWebBucketName:
    Description: Name of the S3 bucket hosting River Guru web app
    Value: !Sub ${WebAppBucketName}-${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-web-bucket-name

  RiverGuruWebsiteUrl:
    Description: URL for River Guru web application
    Value: !Sub http://${WebAppBucketName}-${Environment}.s3-website-${AWS::Region}.amazonaws.com
    Export:
      Name: !Sub ${AWS::StackName}-web-url

  DataApiFunctionName:
    Description: Name of the Data API Lambda function
    Value: !Ref DataApiFunction
    Export:
      Name: !Sub ${AWS::StackName}-data-api-name

  DataApiFunctionArn:
    Description: ARN of the Data API Lambda function
    Value: !GetAtt DataApiFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-data-api-arn
